// lib/scanner/cities.ts
// Top French cities by population — used to seed scan_queue

export const FRENCH_CITIES: readonly string[] = [
  'Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes',
  'Montpellier', 'Strasbourg', 'Bordeaux', 'Lille', 'Rennes',
  'Reims', 'Le Havre', 'Saint-Étienne', 'Toulon', 'Grenoble',
  'Dijon', 'Angers', 'Nîmes', 'Villeurbanne', 'Le Mans',
  'Aix-en-Provence', 'Clermont-Ferrand', 'Brest', 'Tours',
  'Amiens', 'Limoges', 'Annecy', 'Perpignan', 'Boulogne-Billancourt',
  'Metz', 'Besançon', 'Argenteuil', 'Rouen', 'Montreuil',
  'Mulhouse', 'Caen', 'Nancy', 'Saint-Denis', 'Orléans',
  'Avignon', 'Nanterre', 'Courbevoie', 'Roubaix', 'Dunkerque',
  'Tourcoing', 'Créteil', 'Rueil-Malmaison', 'Vitry-sur-Seine',
  'Champigny-sur-Marne', 'Pau', 'Poitiers', 'Asnières-sur-Seine',
  'Versailles', 'Colombes', 'Aubervilliers', 'Aulnay-sous-Bois',
  'Antibes', 'Calais', 'Cannes', 'Bourges', 'La Rochelle',
  'Levallois-Perret', 'Béziers', 'Issy-les-Moulineaux', 'Lorient',
  'Quimper', 'Mérignac', 'Pessac', 'Troyes', 'Valenciennes',
  'Cergy', 'Ivry-sur-Seine', 'Cholet', 'Bayonne', 'Montauban',
  'Meaux', 'Noisy-le-Grand', 'Ajaccio', 'Drancy',
  'Évry-Courcouronnes', 'Vénissieux', 'Épinay-sur-Seine', 'Clichy',
  'Pantin', 'Neuilly-sur-Seine', 'Sartrouville', 'Bobigny',
  'La Courneuve', 'Cherbourg-en-Cotentin', 'Clamart', 'Grasse',
  'Belfort', 'Massy', 'Brive-la-Gaillarde',
  'Laval', 'Montrouge', 'Évreux', 'Colmar', 'Beauvais',
  'Albi', 'Saint-Nazaire', 'Joué-lès-Tours', 'Niort',
  'Hyères', 'Angoulême', 'Charleville-Mézières',
  'Narbonne', 'Saint-Quentin', 'Tarbes', 'Châteauroux', 'Chartres', 'Arles',
  'Chambéry', 'Caluire-et-Cuire', 'Fontenay-sous-Bois', 'Maisons-Alfort',
  'Villejuif', 'Vincennes', 'Bondy',
  'Bagneux', 'Gennevilliers',
  'Vanves', 'Malakoff',
  'Charenton-le-Pont', 'Alfortville',
  'Saint-Ouen', 'Bagnolet', 'Romainville',
  'Noisy-le-Sec', 'Rosny-sous-Bois', 'Gagny',
  'Sevran', 'Livry-Gargan', 'Tremblay-en-France',
  'Villepinte', 'Gonesse',
  'Bezons', 'Cormeilles-en-Parisis',
  'Sarcelles', 'Eaubonne',
  'Franconville', 'Taverny',
  'Pontoise', 'Saint-Germain-en-Laye',
  'Poissy', 'Conflans-Sainte-Honorine',
  'Maisons-Laffitte', 'Chatou',
  'Montesson', 'Houilles',
  'Puteaux',
  'Kremlin-Bicêtre', 'Gentilly',
  'Arcueil', 'Cachan',
  'Rungis', 'Thiais', 'Choisy-le-Roi',
  'Joinville-le-Pont', 'Saint-Maur-des-Fossés',
  'Fort-de-France', 'Cayenne', 'Saint-Denis de la Réunion',
] as const
